apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
  name: {{.NvIpam.PoolName}}
  namespace: {{.NetworkOperator.Namespace}}
spec:
  subnet: {{(index .NvIpam.Subnets 0).Subnet}}
  perNodeBlockSize: 50
  gateway: {{(index .NvIpam.Subnets 0).Gateway}}