apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ethernet-sriov
  namespace: {{.NetworkOperator.Namespace}}
spec:
  deviceType: netdevice
  mtu: {{.Sriov.Mtu}}
  nodeSelector:
    feature.node.kubernetes.io/pci-15b3.present: "true"
  nicSelector:
    vendor: "15b3"
  isRdma: true
  numVfs: {{.Sriov.NumVfs}}
  priority: {{.Sriov.Priority}}
  resourceName: {{.Sriov.ResourceName}}