{{if .Macvlan.SeparateNetworkPerDevice}}
{{/* Create separate IP pools for each network interface */}}
{{range $i, $iface := .ClusterConfig.NvidiaNICs.PF.NetworkInterfaces}}
apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
  name: {{$.NvIpam.PoolName}}-{{printf "%c" (add 97 $i)}}
  namespace: {{$.NetworkOperator.Namespace}}
spec:
  subnet: {{(index $.NvIpam.Subnets $i).Subnet}}
  perNodeBlockSize: 50
  gateway: {{(index $.NvIpam.Subnets $i).Gateway}}
{{if ne $i (sub (len $.ClusterConfig.NvidiaNICs.PF.NetworkInterfaces) 1)}}---{{end}}
{{end}}
{{else}}
{{/* Create single shared IP pool or just first device pool */}}
apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
  name: {{.NvIpam.PoolName}}
  namespace: {{.NetworkOperator.Namespace}}
spec:
  subnet: {{(index .NvIpam.Subnets 0).Subnet}}
  perNodeBlockSize: 50
  gateway: {{(index .NvIpam.Subnets 0).Gateway}}
{{end}}